name: Flight Booking CICD

on:
  push:
    branches:
        - dev
        - main 

jobs:
  upload-to-dev:
    if: github.ref == 'refs/heads/dev' 
    runs-on: ubuntu-latest

    steps:
    #Checkout the repository
    - name: Checkout Code      
      uses: actions/checkout@v3

      # Authentiacate to GCP
    - name: Authenticate to GCP   
      uses: google.github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY  }}

      #Setup Google Cloud SDK
    - name: Setup Google Cloud SDK     
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID}}

      #UPLOAD 'variable_json' to Composer bucket
      







